### PR TITLE
Recorded future: Update - Add "alerts" compatibility to integration

### PR DESCRIPTION
**Pull request by rderkachrf**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
Recorded Future alerts were added to the integration.  There is now the ability to get the alert details, update them or pull them into the system. As well we renamed some of the alerts related commands to better describe the action.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by dgopani-crest** [comment]
Hi @rderkachrf, 
We have updated a few changes in the few files. Can you please review and approve the changes of https://github.com/splunk-soar-connectors/recordedfuture/pull/3/commits/d8f74cdd2e6acef389b6493495f84dbacdc52b0c? 
Changes are:

- No need to create `<release_version>.md` so deleted `4.0.0.md`. It will automatically be generated once merge the PR in the next branch based on the `unreleased.md` file
- Headers are no more required in release notes as Splunk base has default release date
- Updated folders and versions in wheels files
- Other SOAR apps best practices changes

Please let us know in case of any queries.

**Review by btavethiya-crest — COMMENTED** [review]
do we add such file?

**Comment by dgopani-crest** [comment]
> do we add such file [RELEASENOTES.md]?

It is a community app and this file was already there in the previous release.

**Review by btavethiya-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Comment by rderkachrf** [comment]
@dgopani-crest thanks for the review.  The changes https://github.com/splunk-soar-connectors/recordedfuture/commit/d8f74cdd2e6acef389b6493495f84dbacdc52b0c look good.

**Review by tonyc-phantom — APPROVED** [review]

**Pull request merged**
