### PR TITLE
Recorded future: Feature - New actions connected to RF APIs

### PR DESCRIPTION
**Pull request by nestoor22**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- On_poll functionality to download Playbook alerts
- New actions (list_create, list_search, list_details, list_add-entity, list_remove-entity, list_entities, list_status, playbook_alerts_search, playbook_alert_details, update_playbook_alert)

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by dhwanis-crest** [comment]
Hi @nestoor22,
We are changing the min_phantom_version to 5.5.0. Is it fine for you?

**Review by mishalp-crest — APPROVED** [review]

**Review by achandya-crest — APPROVED** [review]

**Comment by dhwanis-crest** [comment]
Hi @nestoor22,
We have fixed the pipeline failures and all the pipelines are passing now. As this app is partner supported, we will not be merging this MR. Please proceed with the release activity from your end.

**Comment by nestoor22** [comment]
> Hi @nestoor22, We are changing the min_phantom_version to 5.5.0. Is it fine for you?

Hi! Yes, it is fine

**Comment by dhwanis-crest** [comment]
Hi @nestoor22, as mentioned above, this app is partner supported. So, we are not going to Merge this PR. If you are not from Recorded Future team, you can contact **"support@recordedfuture.com"** to get your PR merged and perform release activites.

**Comment by nestoor22** [comment]
> Hi @nestoor22, as mentioned above, this app is partner supported. So, we are not going to Merge this PR. If you are not from Recorded Future team, you can contact **"[support@recordedfuture.com](mailto:support@recordedfuture.com)"** to get your PR merged and perform release activites.

Hi! I'm from the Recorded Future team, we are currently waiting a little bit. What is the next step for release? Should I merge this PR by myself when we are ready?

**Comment by nestoor22** [comment]
Hi @dhwanis-crest ! We are ready to release, let me know if I can merge this PR

**Comment by dhwanis-crest** [comment]
Hi @nestoor22, Nothing pending from our end too. If you have the rights, you can feel free to merge this.

**Comment by nestoor22** [comment]
> Hi @nestoor22, Nothing pending from our end too. If you have the rights, you are feel free to merge this.

I have no write access in repository to merge it, could you help?

**Comment by nestoor22** [comment]
Hi @dhwanis-crest ! Any updates about write access?

**Comment by dhwanis-crest** [comment]
Hi @nastorSplunk, Can you please guide @nestoor22  for the release activity. Also, provide the merge rights as this app is partner-supported.

**Comment by nastorSplunk** [comment]
Following up with Michael DiBella to verify access.

**Comment by nastorSplunk** [comment]
@nestoor22, I updated your perms. Let me know if that works

**Comment by nestoor22** [comment]
> @nestoor22, I updated your perms. Let me know if that works

@nastorSplunk Yes, I have "write" permissions. I'm going to merge it if nothing blocking from your side

**Pull request merged**
